implement standalone functionality of FoamDictParser
greole/owls pull request #22
Opened 2023-04-21 11:33 UTC by lupeterm

also, fixes some pyparsing naming errors, e.g., chenging `set_results_name` to `setResultsName`.
fixes #21

2023-04-23 07:23 UTC, greole requested changes
Hey @lupeterm, thanks for your PR. I think that goes into the right direction. Could you  

1. Just revert back to `snake_case` for pyparsing as it seems to be the newer syntax.
2. Add a unit test to [owls/test//test_dictParser.py](https://github.com/greole/owls/tree/Owls2.0/tests/test_dictParser.py)
 for the functionality. Maybe by just take this [controlDict](https://github.com/OpenFOAM/OpenFOAM-10/blob/master/tutorials/incompressible/simpleFoam/airFoil2D/system/controlDict) as an example and write it to a `tmpDir` fixture

2023-04-23 07:23 UTC, greole commented on src/Owls/parser/FoamDict.py
> +        ).setResultsName("of_dimension_set")
I think the changed it the other way around, setResultsName is deprecated in favour of set_results_name

2023-04-23 07:23 UTC, greole commented on src/Owls/parser/FoamDict.py
> +        ).setResultsName("of_dimension_set")
See https://pyparsing-docs.readthedocs.io/en/latest/pyparsing.html?highlight=setResultsName#pyparsing.ParserElement.setResultsName

2023-04-23 07:23 UTC, greole commented on src/Owls/parser/FoamDict.py
> +            + pp.OneOrMore(pp.Word(pp.alphanums + '_-."/'), stopOn=pp.Literal(")"))
I think pyparsing switched from camelCase to snake_case, see https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html#pep-8-naming

2023-04-25 11:27 UTC, lupeterm commented on src/Owls/parser/FoamDict.py
> +        ).setResultsName("of_dimension_set")
Thanks @greole, i reverted my changes back to the non-deprecated version. Somehow, the snake-case spelling threw a couple errors the first time.

2023-04-25 12:06 UTC, greole commented on src/Owls/parser/FoamDict.py
> +                        tmp_list = res.get("of_list").asList()
keep it as_list()
```suggestion
                        tmp_list = res.get("of_list").as_list()
```

2023-04-25 12:08 UTC, greole commented on src/Owls/parser/FoamDict.py
> +                if res.getName() == "key_value_pair":
keep snake case?
```suggestion
                if res.get_name() == "key_value_pair":
```

2023-04-25 12:09 UTC, greole commented on src/Owls/parser/FoamDict.py
> +    def convert_to_number(self, inp):
why do we remove the type hint here?

2023-04-25 12:10 UTC, greole commented on src/Owls/parser/FoamDict.py
> +        self.parse = self.config_parser.searchString(s)
keep snake case?
```suggestion
        self.parse = self.config_parser.search_string(s)
```

2023-04-25 12:55 UTC, greole commented on src/Owls/parser/FoamDict.py
> +
```suggestion
    def get(self, key, default=None):
            return self._dict.get(key, default)
```
I think it is better to just forward get to self._dict

2023-04-25 13:03 UTC, lupeterm commented on src/Owls/parser/FoamDict.py
> +    def convert_to_number(self, inp):
I pushed it by mistake. Iirc, up until Python 3.10, the `list` annotation needed to be imported like `from typing import List`.  I only recently upgraded to 3.10.

2023-04-25 13:06 UTC, lupeterm commented on src/Owls/parser/FoamDict.py
> +
I did not know there was a default option for `dict.get()`. Good to know, thanks!

2023-04-25 13:22 UTC, merged